### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'commit'

### ISSUE THREAD

**Issue by hikkiii** [x-spiders/baiduyun-spider#3]
python /home/ln/下载/baiduyun-spider-master/bin/spider.py --seed-user
success to fetched hot users: 24
Traceback (most recent call last):
  File "/home/ln/下载/baiduyun-spider-master/bin/spider.py", line 492, in <module>
    spider.seedUsers()
  File "/home/ln/下载/baiduyun-spider-master/bin/spider.py", line 334, in seedUsers
    self.db.commit()
  File "/home/ln/下载/baiduyun-spider-master/bin/spider.py", line 92, in commit
    self.dbconn.commit()
AttributeError: 'NoneType' object has no attribute 'commit'

**Comment by Mr-Tommy** [comment]
你的这个问题解决了么。我也碰到了这个问题

**Comment by yijingping** [comment]
是数据库名不对，或者连接不上的原因，或者没有安装MySQLdb
